<a href="https://colab.research.google.com/github/Ochola-Dan/FirstRepo/blob/master/CloudTrack1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1 a)Import numpy; Print (numpy.version.version) #numpy version
   Import pandas as pd; print (pd.__version__) #numpy version

In [4]:
import numpy
print(numpy.version.version)
import pandas as pd
print(pd.__version__)

1.23.5
1.5.3


2) Write a program to print 'Hello HCIA PDTP-Huawei Team’

In [5]:
print('Hello HCIA PDTP-Huawei Team')

Hello HCIA PDTP-Huawei Team


3) Write a program to define two variables, calculate their sum and display the results

In [6]:
num1 = 15
num2 = 20
total = num1+num2
print(f' The sum of {num1} and {num2} is {total}')

 The sum of 15 and 20 is 35


4)
a) Write a program to define a tuple that contains only one element.
b) Write a program to define a tuple and then use the 'for loop' to print all the elements.

In [9]:
student1 =('George')
student2 = ("Mary", 25, "Female")
for item in student2:
  print(item)

Mary
25
Female


5) Write code to create a Python dictionary (the dict type) and print out the details. Add two entries to the dictionary: Associate the key ‘name’ with the value ‘Reagan’, and associate the key ‘phone’ with ‘+254 722 222333’

In [11]:
personal_details = { "Reagan": "+254 722 222333",
                    "George": "+254 712 345678"}
for key, value in personal_details.items():
  print(f"{key}: {value}")



Reagan: +254 722 222333
George: +254 712 345678


a) Define a function to do Multiplication, such as Mul(8,6),and it output 42


In [12]:
my_dict = {}
my_dict['name'] = 'Reagan'
my_dict['phone'] = '+254 722 222333'
print(my_dict)


{'name': 'Reagan', 'phone': '+254 722 222333'}


In [14]:
def Mul(x,y)
    return x* y

result = Mul(8,6)
print(result)


48


b) Complete the function definition so it returns the square of the product of the parameters, so sqrProd(2, 5) returns (2*5)*(2*5) = 100.
def sqrProd(x, y):

In [16]:
def sqrProd(x,y):
  return (x*y)**2

result = sqrProd(2,5)
print(result)

100


7) Import numpy and then:
a) Use numpy to define an array, the shape of it is (5,5) and all elements of it is 0.


In [18]:
import numpy as np

array_zeros = np.zeros((5,5), dtype=int)
print(array_zeros)



[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


 b) Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
matrix_values = np.arange(9).reshape(3,3)
print(matrix_values)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


c) Find indices of non-zero elements from [1,2,0,0,4,0]

In [20]:
non_zero_indices = np.nonzero([1,2,0,0,4,0])
print(non_zero_indices)

(array([0, 1, 4]),)


d) Create a 10x10 array with random values and find the minimum and maximum values

In [30]:
random_array = np.random.randint(low=1, high=100, size=(10,10))
min_value = np.min(random_array)
max_value = np.max(random_array)
print(random_array)
print(f"Minimum value: {min_value}\nMaximum value: {max_value}")

[[89 23 99 93 20 84 28 10 79 83]
 [32  2 56 57 88 91 69 11  3 39]
 [44 37  4 94 62 57 34 17 38 78]
 [ 5 96  8 73 57 19 23 56  7 11]
 [50 76 90  4 35 74 18 88 18 90]
 [65 17 35 86 81 72 13 24 30 53]
 [29 10 60 44 24 39 68 60 30 26]
 [55 92 41  6 29 92 47 84 80 41]
 [ 9 98 82 61 91 42 20 94 47 86]
 [73 52 27 26 90 57 46 93  4 85]]
Minimum value: 2
Maximum value: 99


 e) Create a random vector of size 30 and find the mean value

In [32]:
random_vector = np.random.random(30)
mean_value = np.mean(random_vector)
print(f"Mean value: {mean_value}")

Mean value: 0.4688239696584417


8) Write a Python program that prompts the user for two numbers, reads them in, and prints out the product, labeled appropriately.
9) Complete the code for the following function so it matches its documentation:
def doubleList(numberList):
For each of the numbers in the list numberList, print a line containing twice the original
number. For example,
doubleList ([3, 1, 5]) would print 6, 2, 10

In [33]:
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
product = num1 * num2
print(f"The product of {num1} and {num2} is {product}")

Enter the first number: 12
Enter the second number: 13
The product of 12.0 and 13.0 is 156.0


9) Complete the code for the following function so it matches its documentation: def doubleList(numberList): For each of the numbers in the list numberList, print a line containing twice the original number. For example, doubleList ([3, 1, 5]) would print 6, 2, 10

In [39]:
def doubleList(numberList):
  for num in numberList:
    print(2 * num)

doubleList([3, 1, 5])




6
2
10
